rotationalio/pyensign

generate.sh
pyensign/api/v1beta1/ensign_pb2.py
pyensign/api/v1beta1/ensign_pb2_grpc.py
pyensign/api/v1beta1/event_pb2.py
pyensign/api/v1beta1/topic_pb2.py
pyensign/connection.py
tests/pyensign/test_connection.py

This adds a class for establishing an (insecure) connection to Ensign and a start to the gRPC stubs.

Ensign connection

---

.github/workflows/test.yaml
generate.sh

This adds a basic GitHub workflow for building the python code including the protocol buffers and running the tests.

Add CI tests

---

pyensign/connection.py
requirements.txt
tests/pyensign/test_connection.py

This adds the rest of the client methods to abstract the gRPC interactions to the rest of the SDK.

gRPC client stubs

---

pyensign/connection.py
pyensign/exceptions.py
tests/pyensign/test_connection.py
tests/pyensign/test_exceptions.py

This adds basic exception handling to the methods which invoke gPRC calls.

grpc exception handling

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/generic_issue.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

This PR establishes a preliminary contributor's guide for PyEnsign

Prelim contributor's guide

---

pyensign/ensign.py
pyensign/exceptions.py
pyensign/utils/cache.py
tests/pyensign/test_ensign.py
tests/pyensign/utils/test_cache.py

This PR fixes #18 which requested a feature to allow the Ensign client to cache topic IDs to avoid repeated requests to Ensign.
1. Added a `Cache` utility (naive for now)
2. Updated the Ensign client to use the cache by default, and an option to disable it
3. Added tests for topic_id and topic_exists

Topic cache

---

pyensign/connection.py
pyensign/ensign.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py

This PR implements the project info client method to fetch statistics about the user's project (the project they are authenticated for with their credentials).
1. Added the gRPC method and the user-facing method
2. Added tests for the new method

Project info method

---

pyensign/ensign.py
tests/pyensign/test_ensign.py
tests/requirements.txt

This PR adds an API for the user to ensure a topic exists. Ensure means to check if the topic exists, otherwise create it.
1. Added missing pytest-asyncio package to tests/requirements.txt
2. Added `ensure_topic_exists` to the Ensign client
3. Changed `create_topic` to return the topic ID instead of the protobuf topic

Ensure topic

---

pyensign/connection.py
pyensign/ensign.py
pyensign/exceptions.py
pyensign/iterator.py
pyensign/stream.py
pyproject.toml
tests/conftest.py
tests/pyensign/test_connection.py

This PR is a pretty big refactor of the internal stream management code, but it separates the functionality so it can be tested better and implements automatic stream reconnects.
1. Publish and subscribe streams now reconnect automatically if the stream drops
2. Changed API so the client ID is generated automatically and exists for the lifetime of the client
3. Changed `ack_callback` and `nack_callback` to `on_ack`, `on_nack` for clarity
4. Refactoring iterators and coroutines into classes

Reconnect to stream

---

pyensign/auth/client.py
pyensign/version.py
requirements.txt
tests/requirements.txt

This PR addresses a compatibility issue with use of the requests package. This [issue](https://github.com/urllib3/urllib3/issues/2168) discusses `urllib3` dropping support for OpenSSL < 1.1.1. PyEnsign doesn't use HTTPs, but it does have to make HTTP requests to retrieve credentials on behalf the user. We want to support Python < 3.10 even if users have older versions of OpenSSL installed so this PR implements the HTTP requests using the builtin `urllib` instead.
1. Remove `requests` and `urllib3` from `requirements.txt`
2. Implemented HTTP requests with `urllib` instead of `urllib3`

Deprecate use of requests package

---

pyensign/connection.py
pyensign/ensign.py
pyensign/exceptions.py
pyensign/stream.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py

This PR allows topic names or IDs to be provided to `publish` and `subscribe`.
1. Parse topic names on subscribe
2. Parse topic map on open stream
3. Increase test coverage for publish/subscribe API

Allow topic names for subscribe

---

pyensign/api/v1beta1/event.py
pyensign/connection.py
pyensign/ensign.py
pyensign/events.py
pyensign/exceptions.py
pyensign/iterator.py
pyensign/stream.py
pyensign/utils/queue.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py

This updates the ack/nack handling to give more control and a better event interface to the user.
1. Updated the Event helper class to have state
2. Updated publish stream handler set ack/nack on the Events
3. Changed subscribe to have `on_event` callbacks rather than returning an iterator

Publish and subscribe acks and nacks

---

.gitignore
.pre-commit-config.yaml
pyensign/ensign.py
tests/fixtures/cred.json
tests/fixtures/cred.txt
tests/fixtures/cred_missing.json
tests/pyensign/test_ensign.py

This PR fixes #issue_number _(If you are fixing a bug)_ which reported a bug that caused a problem to occur when users...
_(or if you are introducing a new feature)_ which requested a feature to allow the user to...
1.
2.
3.
Still to do:
Questions for the @rotationalio/maintainers:

Allow creds file

---

.github/workflows/test.yaml
.gitignore
.pre-commit-config.yaml
DESCRIPTION.md
README.md
pyensign/api/v1beta1/event.py
pyensign/auth/client.py
pyensign/connection.py
pyensign/ensign.py
pyensign/events.py
pyensign/exceptions.py
pyensign/iterator.py
pyensign/stream.py
pyensign/utils/queue.py
pyensign/version.py
pyproject.toml
requirements.txt
tests/conftest.py
tests/fixtures/cred.json
tests/fixtures/cred.txt
tests/fixtures/cred_missing.json
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py
tests/requirements.txt

This PR fixes #issue_number _(If you are fixing a bug)_ which reported a bug that caused a problem to occur when users...
_(or if you are introducing a new feature)_ which requested a feature to allow the user to...
1.
2.
3.
Still to do:
Questions for the @rotationalio/maintainers:

Release v0.7.1b1

---

README.md
pyensign/ensign.py
pyensign/publisher.py
pyensign/subscriber.py
tests/pyensign/test_ensign.py
tests/pyensign/test_publisher.py
tests/pyensign/test_subscriber.py

This PR introduces high level publishers and subscribers that provide a more object oriented interface for publishing and subscribing. These can be used with inheritance to implement specific interactions with other APIs or simply as a way to avoid writing async code.
1. Added Publisher and Subscriber classes
2. Added tests

High level publishers subscribers

---

pyensign/exceptions.py
tests/pyensign/test_ensign.py
tests/pyensign/test_exceptions.py
tests/pyensign/test_publisher.py
tests/pyensign/test_subscriber.py

This PR adds information about gRPC errors to the exception returned to the user, in order to diagnose exceptions better.
1. Extend EnsignRPCError to include the status code, name, and details
2. Increase exception coverage for the internal client methods
3. Fix test bug where user's environment was interfering with publisher/subscriber tests

Add grpc exception info

---

pyensign/connection.py
pyensign/ensign.py
pyensign/exceptions.py
pyensign/stream.py
pyensign/utils/cache.py
pyensign/utils/topics.py
tests/conftest.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py
tests/pyensign/test_exceptions.py

This PR fixes a bug where publish doesn't accept topic names on the first call. This was because PyEnsign didn't know about the available topics because it hadn't opened a stream to Ensign yet. The fix is to move the topic validation down into the client.
1. Allow topic names on first publish
2. Add `Topic` class for easier topic management throughout the code
3. Added `--creds` option to allow live tests to load Ensign credentials from JSON file

Allow topic names on first call

---

README.md

This PR update the README code to use the more user-friendly mimetypes.

Fix mimetype in README

---

DESCRIPTION.md
README.md
pyensign/connection.py
pyensign/ensign.py
pyensign/stream.py
pyensign/subscriber.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py
tests/pyensign/test_stream.py
tests/pyensign/test_subscriber.py

This PR goes back to the older method of subscribing which is a lot more understandable.
1. Revert to `async for` syntax for subscribe
2. Ensure timeout propagate back to users
3. Update tests
4. Update docs

Revert to async for syntax for subscribe

---

pyensign/iterator.py
tests/pyensign/test_iterator.py

This PR adds test coverage for `iterator.py`

Iterator tests

---

README.md
pyensign/connection.py
pyensign/ensign.py
pyensign/publisher.py
pyensign/subscriber.py
tests/conftest.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py
tests/pyensign/test_subscriber.py

This PR fixes a deprecation warning that was happening in Python 3.10 when users try to execute Ensign API calls in the event loop, e.g.
```python
ensign = Ensign()
async def publish():
await ensign.publish("topic", events)
asyncio.get_event_loop().run_until_complete(publish())
```
The underlying issue is that when the gRPC aio library creates a channel, it checks if there is an existing event loop and creates one if it doesn't exist. However we were creating the channel on the `Ensign()` call which happens in synchronous code, so the user probably doesn't have an event loop. This causes a situation where user code wants to create the event loop but gRPC has already created an event loop - so we either need to attach to the gRPC event loop or start the channel from within an event loop …

Move gRPC channel creation to call time

---

pyensign/nack.py
tests/pyensign/test_events.py

This PR fixes #46 by adding more convenient Nack code constants for developers.
1. Add nack code constants to `pyensign/nack.py`
2. Add a test to verify constants can be imported and used.

Easier nack codes

---

pyensign/auth/interceptor.py
pyensign/connection.py
tests/pyensign/test_connection.py

This PR adds auth interceptors to allow for custom error handling on the per-RPC authentication and ensures that credentials can be used if insecure=True (for local testing only).
1. Add client interceptors for adding authentication metadata (previously a metadata callback was used)
2. Support insecure=True and auth (local testing mode)

Auth interceptors

---

pyensign/auth/client.py
tests/pyensign/auth/test_client.py

This PR fixes a bug where PyEnsign gave up trying to authenticate if the refresh attempt failed.
1. Changed logic to reauthenticate by calling the authenticate endpoint again if refresh raises an error.
2. Added test cases to cover the logic.

Reauthenticate logic

---

README.md
pyensign/events.py
pyensign/mimetypes.py
pyensign/utils/pbtime.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py
tests/pyensign/test_events.py

This PR adds some debug utilities for understanding the data and metadata that's encoded in an Event.
1. Add Type helper class with semver parsing
2. Add __str__ and __repr__ methods to the Event helper class

Event debugging helpers

---

pyensign/auth/interceptor.py
pyensign/connection.py
pyensign/ensign.py
pyensign/exceptions.py
pyensign/utils/pbtime.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py
tests/pyensign/test_exceptions.py

This PR adds support for EnSQL queries via the `query` method on the client.
1. Implemented the `query` method on the client
2. Updated tests

EnSQL client methods

---

README.md
pyensign/connection.py
pyensign/ensign.py
pyensign/events.py
tests/pyensign/test_ensign.py

This PR adds a `publish` decorator to hopefully make it easier to integrate Ensign into existing applications. The decorator can only be applied to async functions and treats the return value as the event payload, handling the encoding automatically or using the provided encoder.
1. Added authenticate decorator
2. Added publish decorator
3. Test coverage

Publish decorator

---

README.md
pyensign/ensign.py
tests/pyensign/test_ensign.py

This PR adds a subscriber decorator which can be used to define subscriber functions. Subscriber functions either accept an iterator with the events or define the iterator that processes the events.
1. Added subscriber decorator and tests
2. Change publish decorator to `publisher`

Add subscriber decorator

---

pyensign/ensign.py
pyensign/events.py
pyensign/projects.py
pyensign/topics.py
pyensign/utils/topics.py
pyensign/utils/ulid.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py
tests/pyensign/test_stream.py

This PR adds data classes for the Project, Topic, and EventType data structures so that a more usable response is returned from the Info method.

Improve project info

---

pyensign/connection.py
pyensign/ensign.py
pyensign/exceptions.py
tests/pyensign/test_connection.py
tests/pyensign/test_ensign.py

This PR updates the `destroy_topic` method to accept topic names as well as IDs.

Allow topic names for destroy topic

---

pyensign/auth/client.py

This PR adds handling for unexpected exceptions during client authentication so that they are re-raised as `AuthenticationError`.

Add authenticate unexpected error handling
